pipeline {
    agent any
    tools {
        jdk 'jdk21'
        // flutter 'Flutter SDK'
    }
        environment {
            JAVA_HOME = '/usr/lib/jvm/java-21-openjdk-amd64'
            FLUTTER_HOME = "/opt/flutter"
            ANDROID_HOME = "/opt/android-sdk"
            PATH = "${FLUTTER_HOME}/bin:${ANDROID_HOME}/cmdline-tools/latest/bin:${ANDROID_HOME}/platform-tools:${PATH}"
        }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', changelog: false, credentialsId: '71294f3e-d70d-491d-9c6f-a3baa1121c45', poll: false, url: 'https://github.com/Haseef-Ahamed/Pizza-Order-Management-System.git'
                echo 'Checking out source code...'
                // Add checkout steps here
            }
        }
        stage('Set up JDK') {
            steps {
                echo 'Setting up JDK environment...'
                sh 'java -version'
                echo 'JDK environment set up successfully.'
            }
        }
        stage('Set up Flutter') {
            steps {
                echo 'Setting up Flutter environment...'
                sh 'flutter --version'
                echo 'Flutter environment set up successfully.'
            }
        }
        stage('install dependencies') {
            steps {
                echo 'Installing dependencies...'
                sh 'flutter pub get'
                echo 'Dependencies installed successfully.'
                // Add dependency installation steps here
            }
        }
        stage('Build Android APK') {
            steps {
                echo 'Building...'
                sh 'flutter build apk --release'
                echo 'Build completed successfully.'
                // Add build steps here
            }
        }
        // stage('Build iOS IPA') {
        //     steps {
        //         echo 'Building...'
        //         sh 'flutter build ios --release'
        //         echo 'Build completed successfully.'
        //         // Add build steps here
        //     }
        // }
        stage('Archive Artifacts') {
            steps {
                echo 'Archiving artifacts...'
                archiveArtifacts artifacts: 'build/app/outputs/flutter-apk/app-release.apk', fingerprint: true
                echo 'Artifacts archived successfully.'
                // Add artifact archiving steps here

                // echo 'Archiving iOS artifacts...'
                // archiveArtifacts artifacts: 'build/ios/ipa/*.ipa', fingerprint: true
            }
        }
        stage('Test') {
            steps {
                echo 'Testing...'
                sh 'flutter test'
                echo 'All tests passed successfully.'
                // Add test steps here
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying...'
                // Add deploy steps here
            }
        }
    }
}